### ISSUE TITLE
Feature request: plot.scatter with text marker?

### ISSUE THREAD

**Issue by brezn1** [spotify/chartify#44]
FEATURE REQUEST

E.g.:

```python
ch.plot.scatter(
    data_frame=price_and_quantity_by_country,
    x_column='total_price',
    y_column='quantity',
    color_column='country')

ch.plot.text(
    data_frame=price_and_quantity_by_country,
    x_column='total_price',
    y_column='quantity',
    text_column='country',
    color_column='country',
    x_offset=1,
    y_offset=-1,
    font_size='10pt')
```

I understand there is a very good reason to separate the data- and the text-plot, but wouldn't it be more efficient to inject the text-marker-"data" directly into scatter.plot, or any kind of plot? 

Like a switch. If text data is present, render the data & text?

Something like this:

```python
ch.plot.scatter(
    data_frame=price_and_quantity_by_country,
    x_column='total_price',
    y_column='quantity',
    color_column='country',
    text_column='country',
    x_offset=1,
    y_offset=-1,
    font_size='10pt')
```

**Comment by cphalpert** [comment]
Thanks for the suggestion but I would prefer not to bundle the functionality for now.

A separate text method would still be needed for when users want to plot text alone, so bundling wouldn't reduce the number of methods.

It would also create a more confusing experience when users are creating scatter plots without text since the extra parameters `x_offset`, `y_offsite`, `font_size` that wouldn't apply to the operation.
